export const meditations = [
  {
    id: "1",
    title: "Autumn Sky Meditation",
    duration: "10:00",
    description: "Gentle rain sounds for deep relaxation",
    image: require("../assets/images/1.png"),
  },
  {
    id: "2",
    title: "Calm Soul Meditation",
    duration: "15:00",
    description: "Calming ocean waves for stress relief",
    image: require("../assets/images/2.jpg"),
  },
  {
    id: "3",
    title: "Deep Meditation",
    duration: "20:00",
    description: "Immerse yourself in nature sounds",
    image: require("../assets/images/3.png"),
  },
  {
    id: "4",
    title: "Immersive Meditation",
    duration: "12:00",
    description: "Dive into a serene meditative experience",
    image: require("../assets/images/4.png"),
  },
  {
    id: "5",
    title: "Meditation Music Without Nature Sound",
    duration: "18:00",
    description: "Peaceful melodies without nature distractions",
    image: require("../assets/images/5.png"),
  },
  {
    id: "6",
    title: "Meditation Music",
    duration: "14:00",
    description: "Soothing tones to calm your mind",
    image: require("../assets/images/6.png"),
  },
  {
    id: "7",
    title: "Relaxing Meditation",
    duration: "16:00",
    description: "A blend of soft music and calming vibes",
    image: require("../assets/images/7.png"),
  },
  {
    id: "8",
    title: "The Old Water Mill Meditation",
    duration: "13:00",
    description: "Relaxing sounds of a historic water mill",
    image: require("../assets/images/8.png"),
  },
  {
    id: "9",
    title: "The Waterfall Meditation",
    duration: "22:00",
    description: "The tranquil rush of a serene waterfall",
    image: require("../assets/images/9.png"),
  },
];
